//! Build script for the GUI binary.
//!
//! On Windows, embeds the application icon (`app_icon.ico`) into the executable
//! so Explorer, the taskbar, and Alt-Tab show it. On other platforms this is a
//! no-op.

fn main() {
    // Re-run if the icon or resource script changes.
    println!("cargo:rerun-if-changed=app_icon.rc");
    println!("cargo:rerun-if-changed=src/resources/app_icon.ico");
    println!("cargo:rerun-if-changed=src/license.rs");
    println!("cargo:rerun-if-env-changed=LICENSE_SALT");

    // `src/license.rs` holds the license-key HMAC salt and is intentionally
    // git-ignored (a secret). For fresh clones / CI where the file is absent,
    // generate it from the LICENSE_SALT env var, or a build-only placeholder so
    // the crate still compiles. Never overwrite a developer's existing file.
    let license_path = std::path::Path::new("src/license.rs");
    if !license_path.exists() {
        let salt = std::env::var("LICENSE_SALT").unwrap_or_else(|_| "UNSET-BUILD-SALT".to_string());
        let contents = format!(
            "//! Auto-generated by build.rs because src/license.rs was absent.\n\
             //! Provide the real salt via the LICENSE_SALT env var or a committed-\n\
             //! out-of-band file. This file is git-ignored.\n\n\
             pub const LICENSE_SALT: &str = \"{salt}\";\n"
        );
        let _ = std::fs::write(license_path, contents);
    }

    #[cfg(target_os = "windows")]
    {
        // Generate a version-info resource so Explorer's "Open with" and file
        // properties show a friendly "TagTiger" (via FileDescription) instead
        // of the raw "tagtiger-gui.exe" filename. Combined with the icon.
        let ver = env!("CARGO_PKG_VERSION"); // e.g. "1.0.0"
        let mut parts = ver.split('.').map(|s| s.parse::<u16>().unwrap_or(0));
        let (maj, min, pat) = (
            parts.next().unwrap_or(0),
            parts.next().unwrap_or(0),
            parts.next().unwrap_or(0),
        );
        let out_dir = std::env::var("OUT_DIR").unwrap();
        let rc_path = std::path::Path::new(&out_dir).join("tagtiger_version.rc");
        // The .ico path must be absolute here since the generated .rc lives in
        // OUT_DIR, not the crate root.
        let ico =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/resources/app_icon.ico");
        let ico_str = ico.to_string_lossy().replace('\\', "\\\\");
        let rc = format!(
            "IDI_ICON1 ICON \"{ico}\"\n\
             1 VERSIONINFO\n\
             FILEVERSION {maj},{min},{pat},0\n\
             PRODUCTVERSION {maj},{min},{pat},0\n\
             FILEOS 0x40004L\n\
             FILETYPE 0x1L\n\
             BEGIN\n\
             \x20 BLOCK \"StringFileInfo\"\n\
             \x20 BEGIN\n\
             \x20   BLOCK \"040904b0\"\n\
             \x20   BEGIN\n\
             \x20     VALUE \"CompanyName\", \"Glowing Cat Software\"\n\
             \x20     VALUE \"FileDescription\", \"TagTiger\"\n\
             \x20     VALUE \"FileVersion\", \"{ver}\"\n\
             \x20     VALUE \"InternalName\", \"TagTiger\"\n\
             \x20     VALUE \"OriginalFilename\", \"tagtiger-gui.exe\"\n\
             \x20     VALUE \"ProductName\", \"TagTiger\"\n\
             \x20     VALUE \"ProductVersion\", \"{ver}\"\n\
             \x20   END\n\
             \x20 END\n\
             \x20 BLOCK \"VarFileInfo\"\n\
             \x20 BEGIN\n\
             \x20   VALUE \"Translation\", 0x409, 1200\n\
             \x20 END\n\
             END\n",
            ico = ico_str,
            maj = maj,
            min = min,
            pat = pat,
            ver = ver,
        );
        std::fs::write(&rc_path, rc).expect("write version .rc");
        // The resource is cosmetic (icon + version strings), so a missing
        // manifest toolchain is not fatal.
        embed_resource::compile(&rc_path, embed_resource::NONE)
            .manifest_optional()
            .unwrap();
    }
}
