//! Build script for the GUI binary.
//!
//! On Windows, embeds the application icon (`app_icon.ico`) into the executable
//! so Explorer, the taskbar, and Alt-Tab show it. On other platforms this is a
//! no-op.

fn main() {
    // Re-run if the icon or resource script changes.
    println!("cargo:rerun-if-changed=app_icon.rc");
    println!("cargo:rerun-if-changed=src/resources/app_icon.ico");
    println!("cargo:rerun-if-changed=src/license.rs");
    println!("cargo:rerun-if-env-changed=LICENSE_SALT");

    // `src/license.rs` holds the license-key HMAC salt and is intentionally
    // git-ignored (a secret). For fresh clones / CI where the file is absent,
    // generate it from the LICENSE_SALT env var, or a build-only placeholder so
    // the crate still compiles. Never overwrite a developer's existing file.
    let license_path = std::path::Path::new("src/license.rs");
    if !license_path.exists() {
        let salt = std::env::var("LICENSE_SALT").unwrap_or_else(|_| "UNSET-BUILD-SALT".to_string());
        let contents = format!(
            "//! Auto-generated by build.rs because src/license.rs was absent.\n\
             //! Provide the real salt via the LICENSE_SALT env var or a committed-\n\
             //! out-of-band file. This file is git-ignored.\n\n\
             pub const LICENSE_SALT: &str = \"{salt}\";\n"
        );
        let _ = std::fs::write(license_path, contents);
    }

    #[cfg(target_os = "windows")]
    {
        // `app_icon.rc` references the .ico via a relative path. The resource
        // is cosmetic (icon only), so a missing manifest toolchain is not fatal.
        embed_resource::compile("app_icon.rc", embed_resource::NONE)
            .manifest_optional()
            .unwrap();
    }
}
